export { default as HeavenlyLogo } from './heavenly.png';
export { default as BorealLogo } from './boreal.png';
export { default as ChinaPeakLogo } from './chinapeak.png';
export { default as DiamondPeakLogo } from './diamondpeak.png';
export { default as HomewoodLogo } from './homewood.png';
export { default as JuneLogo } from './june.png';
export { default as KirkwoodLogo } from './kirkwood.png';
export { default as MammothLogo } from './mammoth.png';
export { default as MtRoseLogo } from './mtrose.png';
export { default as NorthstarLogo } from './northstar.png';
export { default as PalisadesLogo } from './palisades.png';
export { default as SierraLogo } from './sierra.png';
export { default as SugarBowlLogo } from './sugarbowl.png';
export { default as TahoeDonnerLogo } from './tahoedonner.png';
export { default as AboutPic } from './about-page-author.jpg';
export { default as TwitterLogo } from './Logo blue.svg';
