export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as About } from './About/About';
export { default as Resort } from './Resort/Resort';
export { default as Resorts } from './Resorts/Resorts';
export { default as Traffic } from './Traffic/Traffic';
export { default as HomeBody } from './HomeBody/HomeBody';
export { default as NotFoundPage } from './NotFoundPage/NotFoundPage';
export { default as Safety } from './Safety/Safety';
