import React from 'react';
import { Paper } from '@mui/material';
import { Routes, Route } from 'react-router-dom';

import './App.css';
import {
   Header,
   Footer,
   About,
   Resort,
   Resorts,
   Traffic,
   Safety,
   HomeBody,
   NotFoundPage,
} from './components';

import {
   HeavenlyLogo,
   BorealLogo,
   ChinaPeakLogo,
   DiamondPeakLogo,
   HomewoodLogo,
   JuneLogo,
   KirkwoodLogo,
   MammothLogo,
   MtRoseLogo,
   NorthstarLogo,
   PalisadesLogo,
   SierraLogo,
   SugarBowlLogo,
   TahoeDonnerLogo,
   WhistlerLogo,
   VailLogo,
   FortyNineLogo,
   ABasinLogo,
   AltaLogo,
   Alyeska,
   AngelFire,
   AspenHighlands,
   AspenMtn,
   Attitash,
   BeaverCreek,
   BigSky,
   BigWhite,
   BlueMtn,
   Bolton,
   Breck,
   Bretton,
   BrianHead,
   Bridger,
   Brighton,
   Bromley,
   Burke,
   Butter,
   Caberfae,
   Camel,
   Canada,
   Cannon,
   Cataloochee,
   Catedral,
   Claviere,
   Copper,
   Coronet,
   Courchevel,
   Cranmore,
   Cransmontana,
   Crested,
   Crystal,
   Cypress,
   Deer,
   Devils,
   Falls,
   Folgaria,
   Folgarida,
   Targ,
   Gore,
   Grouse,
   Gun,
   Hoch,
   Hoodoo,
   Hunter,
   Ischgl,
   Jackson,
   Jay,
   Jiminy,
   Kill,
   Key,
   King,
   Kitz,
   LaPlagne,
   Laro,
   Lava,
   LesArcs,
   LesMen,
   Loon,
   Love,
   MadRiver,
   Madonna,
   Manning,
   Megeve,
   Meri,
   MonteBon,
   Monarch,
   Morz,
   WinterPlace,
   WinterPark,
   Wind,
   Wild,
   White,
   Water,
   Verb,
   Val,
   Trem,
   Timber,
   Thred,
   Tell,
   Taos,
   Sun,
   Sunshine,
   Sunday,
   SunPeaks,
   Loaf,
   Bush,
   Stratton,
   Stevens,
   Stowe,
   Steamboat,
   StAnton,
   Sol,
   Soel,
   Shoe,
   Mass,
   Bird,
   Basin,
   Valley,
   Smuggs,
   Silver,
   ShawneePeak,
   ShawneeMtn,
   Sest,
   Schweit,
   Sasquatch,
   Sauze,
   Sansi,
   Saddle,
   RedMtn,
   RedLodge,
   Ragged,
   Ponte,
   Pico,
   ParkCity,
   Pin,
   Peio,
   Perisher,
   Pats,
   Pag,
   Owls,
   Okemo,
   Niseko,
   Hood,
   MtBrighton,
   MtHigh,
   MtBachelor,
   MtSeymour,
   MtSpokane,
   MtBuller,
   MtHotham,
   MtSnow,
   MtSunapee,

} from './images';

import background from './images/hero_banner.jpg';


export default function App() {
   const resorts = [{ query: 'boreal', skimapID: '523', image: BorealLogo },
   { query: 'chinapeak', skimapID: '527', image: ChinaPeakLogo },
   { query: 'diamondpeak', skimapID: '359', image: DiamondPeakLogo },
   { query: 'heavenly', skimapID: '544', image: HeavenlyLogo },
   { query: 'northstar', skimapID: '531', image: NorthstarLogo },
   { query: 'kirkwood', skimapID: '537', image: KirkwoodLogo },
   { query: 'homewood', skimapID: '545', image: HomewoodLogo },
   { query: 'june-mountain', skimapID: '540', image: JuneLogo },
   { query: 'mammoth-lakes', skimapID: '530', image: MammothLogo },
   { query: 'mtrose', skimapID: '358', image: MtRoseLogo },
   { query: 'palisades', skimapID: '538', image: PalisadesLogo },
   { query: 'alpine', skimapID: '522', image: PalisadesLogo },
   { query: 'sierra', skimapID: '525', image: SierraLogo },
   { query: 'sugarbowl', skimapID: '543', image: SugarBowlLogo },
   { query: 'tahoe-donner', skimapID: '529', image: TahoeDonnerLogo },
   { query: 'whistler-blackcomb', skimapID: '28', image: WhistlerLogo },
   { query: 'vail', skimapID: '507', image: VailLogo },
   { query: '49-degrees-north', skimapID: '195', image: FortyNineLogo },
   { query: 'abasin', skimapID: '513', image: ABasinLogo },
   { query: 'alta', skimapID: '224', image: AltaLogo },
   { query: 'alyeska', skimapID: '552', image: Alyeska },
   { query: 'angel-fire', skimapID: '331', image: AngelFire },
   { query: 'attitash', skimapID: '349', image: Attitash },
   { query: 'beavercreek', skimapID: '497', image: BeaverCreek },
   { query: 'big-sky', skimapID: '361', image: BigSky },
   { query: 'big-white', skimapID: '57', image: BigWhite },
   { query: 'bluemountain', skimapID: '113', image: BlueMtn },
   { query: 'bolton-valley', skimapID: '216', image: Bolton },
   { query: 'breck', skimapID: '510', image: Breck },
   { query: 'brettonwoods', skimapID: '346', image: Bretton },
   { query: 'brianhead', skimapID: '227', image: BrianHead },
   { query: 'bridger-bowl', skimapID: '375', image: Bridger },
   { query: 'brighton', skimapID: '222', image: Brighton },
   { query: 'bromley-mountain', skimapID: '217', image: Bromley },
   { query: 'burke-mountain', skimapID: '208', image: Burke },
   { query: 'buttermilk', skimapID: '504', image: Butter },
   { query: 'caberfae-peaks', skimapID: '404', image: Caberfae },
   { query: 'camelback', skimapID: '238', image: Camel },
   { query: 'canada-olympic-park', skimapID: '21', image: Canada },
   { query: 'cannon', skimapID: '347', image: Cannon },
   { query: 'cataloochee', skimapID: '288', image: Cataloochee },
   { query: 'catedral', skimapID: '1124', image: Catedral },
   { query: 'claviere', skimapID: '2096', image: Claviere },
   { query: 'copper', skimapID: '509', image: Copper },
   { query: 'coronetpeak', skimapID: '1116', image: Coronet },
   { query: 'courchevel', skimapID: '1079', image: Courchevel },
   { query: 'cranmore-mountain', skimapID: '344', image: Cranmore },
   { query: 'cransmontana', skimapID: '991', image: Cransmontana },
   { query: 'crested-butte', skimapID: '514', image: Crested },
   { query: 'crystal-mountain', skimapID: '193', image: Crystal },
   { query: 'cypress-mountain', skimapID: '50', image: Cypress },
   { query: 'deer-valley', skimapID: '223', image: Deer },
   { query: 'devils-head', skimapID: '179', image: Devils },
   { query: 'falls-creek', skimapID: '1164', image: Falls },
   { query: 'folgaria', skimapID: '4227', image: Folgaria },
   { query: 'folgarida-marilleva', skimapID: '2073', image: Folgarida },
   { query: 'gore-mountain', skimapID: '320', image: Gore },
   { query: 'grand-targhee', skimapID: '150', image: Targ },
   { query: 'grouse', skimapID: '58', image: Grouse },
   { query: 'gunstock', skimapID: '342', image: Gun },
   { query: 'hochfuegen', skimapID: '12306', image: Hoch },
   { query: 'hoodoo', skimapID: '268', image: Hoodoo },
   { query: 'hunter', skimapID: '315', image: Hunter },
   { query: 'ischgl-silvretta-arena', skimapID: '630', image: Ischgl },
   { query: 'jackson-hole', skimapID: '151', image: Jackson },
   { query: 'jay-peak', skimapID: '202', image: Jay },
   { query: 'jiminypeak', skimapID: '443', image: Jiminy },
   ]
   // randomly shuffle the ski resorts 
   function shuffle(array) {
      let currentIndex = array.length, randomIndex;

      // While there remain elements to shuffle.
      while (currentIndex != 0) {

         // Pick a remaining element.
         randomIndex = Math.floor(Math.random() * currentIndex);
         currentIndex--;

         // And swap it with the current element.
         [array[currentIndex], array[randomIndex]] = [
            array[randomIndex], array[currentIndex]];
      }

      return array;
   }

   return (
      <Paper>
         <Header />
         <Routes>
            <Route path='/' element={<HomeBody style={{
               backgroundImage: `url(${background})`,
            }} />} />
            <Route path='/about' element={<About />} />
            <Route path='/resorts'
               element={<Resorts resorts={shuffle(resorts)} />} />
            <Route path='/resorts/:resortQuery' element={<Resort resorts={resorts} />} />
            <Route path='/traffic' element={<Traffic />} />
            <Route path='/safety' element={<Safety />} />
            {/* Wild card path leads to a 404 not found page. */}
            <Route path='*' element={<NotFoundPage />} />
         </Routes>
         <Footer />
      </Paper>
   )
};